#!/bin/sh
/usr/bin/sakis3g sudo connect --nostorage --pppd APN="web.gprs.mtnnigeria.net" APN_USER="web" APN_PASS="mtn" USBDRIVER="option" MODEM="12d1:1003"
/usr/bin/sakis3g sudo connect --nostorage --pppd APN="etisalat" APN_USER="apn" APN_PASS="apn" USBDRIVER="option" MODEM="19d2:0117"  
#

